{{ if .Values.graderSetupService.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: illumidesk-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grader-setup-service-{{ .Release.Name }}
  labels:
    app: illumidesk
    component: grader-setup-service-{{ .Release.Name }}
rules:
  - apiGroups:
     - ""
     - extensions
    resources:
     - services
     - pods/status
    verbs:
     - create
     - get
     - list
     - update
     - watch
     - patch
     - delete
  - apiGroups:
      - "apps"
      - extensions
    resources:
      - pods
      - secrets
      - services
      - namespaces
      - deployments
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grader-setup-service-{{ .Release.Name }}
  labels:
    app: illumidesk
    component: grader-setup-service-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grader-setup-service-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: illumidesk-account
    namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: grader-setup-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    component: grader-setup-service
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grader-setup-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: illumidesk
    component: grader-setup-service
spec:
  selector:
    matchLabels:
      component: grader-setup-service
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: illumidesk
        component: grader-setup-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: grader-setup-container
          image: {{ .Values.graderSetupService.graderSetupImage }}
          resources:
            requests:
              cpu: {{ .Values.graderSetupService.graderCpuGuarantee | default "200m" | quote  }}
              memory: {{ .Values.graderSetupService.graderMemGuarantee | default "400Mi" | quote }}
            limits:
              cpu: {{ .Values.graderSetupService.graderCpuLimit | default "400m" | quote }}
              memory: {{ .Values.graderSetupService.graderMemLimit | default "800Mi" | quote }}
          imagePullPolicy: {{ .Values.graderSetupService.pullPolicy }}  
          ports:
            - containerPort: 8000
          env:
            - name: GRADER_IMAGE_NAME
              value: {{ .Values.graderSetupService.graderSpawnerImage | default "illumidesk/grader-notebook:latest" }}
            - name: GRADER_REQUESTS_CPU
              value: {{ .Values.graderSetupService.graderSpawnerCpuGuarantee | default "200m" | quote }}
            - name: GRADER_LIMITS_CPU
              value: {{ .Values.graderSetupService.graderSpawnerCpuLimit | default "400m" | quote }}
            - name: GRADER_REQUESTS_MEM
              value: {{ .Values.graderSetupService.graderSpawnerMemGuarantee | default "400Mi" | quote}}
            - name: GRADER_LIMITS_MEM
              value: {{ .Values.graderSetupService.graderSpawnerMemLimit | default "800Mi" | quote}}
            - name: GRADER_STORAGE
              value: {{ .Values.graderSetupService.graderSpawnerStorage | default "500Mi" | quote }}
            - name: POSTGRES_NBGRADER_HOST
              valueFrom:
                configMapKeyRef:
                  name: hub-illumidesk-cm
                  key: POSTGRES_NBGRADER_HOST
            - name: POSTGRES_NBGRADER_USER
              valueFrom:
                configMapKeyRef:
                  name: hub-illumidesk-cm
                  key: POSTGRES_NBGRADER_USER
            - name: POSTGRES_NBGRADER_PASSWORD
              valueFrom:
                secretKeyRef:
              {{ if .Values.externalDatabase.enabled }}
                  name: {{ .Values.externalDatabase.existingSecret }}
              {{ else if .Values.postgresql.enabled }}
                  name: {{ .Values.postgresql.existingSecret }}
              {{ end }}
                  key: postgresql-password
            - name: ILLUMIDESK_MNT_ROOT
              value: '/illumidesk-courses'
            - name: PORT
              value: "8000"
              # empty string for more logging
            - name: GIN_MODE
              value: ""
            - name: JUPYTERHUB_API_URL
              valueFrom:
                configMapKeyRef:
                  name: hub-illumidesk-cm
                  key: JUPYTERHUB_API_URL
            - name: DEBUG
              value: "true"
            - name: ILLUMIDESK_NB_EXCHANGE_MNT_ROOT
              value: '/illumidesk-nb-exchange'
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: ILLUMIDESK_K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: GRADER_PVC
              value: grader-pvc-{{ .Release.Name }}
            - name: GRADER_SHARED_PVC
              value: shared-pvc-{{ .Release.Name }}
            - name: GRADER_IMAGE_PULL_POLICY
              value: {{ .Values.graderSetupService.graderSpawnerPullPolicy }}
          volumeMounts:
            - name: grader-pv-{{ .Release.Name }}
              mountPath: /illumidesk-courses
              subPath: illumidesk-courses
            - name: shared-pv-{{ .Release.Name }}
              mountPath: /illumidesk-nb-exchange
      serviceAccountName: illumidesk-account
      volumes:
        - name: shared-pv-{{.Release.Name }}
          persistentVolumeClaim:
            claimName: shared-pvc-{{ .Release.Name }}
        - name: grader-pv-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: grader-pvc-{{ .Release.Name }}

{{ end }}