# IllumiDesk configuration values
# --------------------
# Create and use roles and service accounts on an RBAC enabled cluster.
rbac:
  enabled: true
  
jupyterhub:
# Helm config for jupyterhub goes here
# See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml
  hub:
    extraConfig:
      logoConfig: |
        import urllib.request
        urllib.request.urlretrieve("https://configs.illumidesk.com/images/illumidesk-80.png", "/srv/jupyterhub/illumidesk-80.png")
        c.JupyterHub.logo_file = "/srv/jupyterhub/illumidesk-80.png"
    image:
      name: illumidesk/k8s-hub
      tag: latest
      pullPolicy: Always
    shutdownOnLogout: true
  proxy:
    https:
      enabled: true
    secretToken: ''
    service:
      # ports:
      #   nodePort: 8080
      type: ClusterIP
  singleuser:
    cmd: start-singleuser.sh
    extraEnv:
      CHOWN_HOME: 'yes'
      Editor: vim
    fsGid: 0
    uid: 0
    image:
      name: illumidesk/illumidesk-notebook
      tag: latest
      pullPolicy: Always

postgresql:
  enabled: false

datadog:
  enabled: false
  targetSystem: "linux"
  datadog:
    apiKey: ''
    site: ''
    clusterName: ''
    logs:
      enabled: true
      containerCollectAll: true
    clusterAgent:
      enabled: true
      token: ''
      metricsProvider:
        enabled: true

albIngressController:
  enabled: false
  enableIRSA: false

allowExternalDNS: 
  enabled: false
  enableIRSA: false

nginxIngressController:
  enabled: false
  host: 'test'

allowNFS:
  enabled: false

graderSetupService:
  enabled: false
  graderSetupImage: illumidesk/grader-setup-app:latest
  graderImage: illumidesk/illumidesk-grader:latest
