{{ if .Values.albIngressController.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-ingress 
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.albIngressController.ingress.annotations }}
    {{ $key }}: {{ $value }}
  {{- end }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
spec:

  rules:
  - host: {{ .Values.albIngressController.host }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: proxy-public
          servicePort: 80
{{ end }}